### ISSUE TITLE
Extensions not present in v1.0.7

### ISSUE THREAD

**Issue by matija32** [teddymacn/Teddy-MvvmCross-Plugins#2]
Hey, I installed the latest version of the plugin, but the extension methods for the ISimpleAudioPlayer were not exported.
![image](https://cloud.githubusercontent.com/assets/11648405/25564610/4dfe775a-2db7-11e7-97d8-985afa50b446.png)
Got any ideas why?

**Comment by teddymacn** [comment]
looks like in the previous pullrequest, the extension method cs file is not included in the project file, so not built to the DLL. just added and released new version 1.0.8. please try again.

**Comment by matija32** [comment]
Yep, that fixed it.
![image](https://cloud.githubusercontent.com/assets/11648405/25566172/765c5d80-2dd4-11e7-9c80-b597843dac34.png)
